export const mensagens = {
  ERRO_INTERNO: 'Erro interno do servidor',
  ERRO_LISTAR: 'Erro ao listar os dados.',
  ERRO_CADASTRAR: 'Erro ao realizar cadastro.',
  ERRO_ALTERAR: 'Erro ao realizar alteração.',
  ERRO_EXCLUIR: 'Erro ao realizar exclusão.',
  SUCESSO_CADASTRAR: 'Cadastrado com sucesso.',
  SUCESSO_ALTERAR: 'Alterado com sucesso.',
  SUCESSO_EXCLUIR: 'Excluído com sucesso',
  ID_INVALIDO: 'ID inválido!',
  ID_NAO_ESPECIFICADO: 'ID não especificado.',
  DADO_NAO_ENCONTRADO: 'Nenhum dado encontrado.',
  INFORMACAO_OBRIGATORIA: 'Este campo é obrigatório!',
  TOKEN_INVALIDO: 'Token fornecido inválido',
};
